image: beabys/centos7_golang:latest

variables:
  CI_TAG_VERSION: 'v1.0.0'

before_script:
  - |- 
    if [[ $CI_COMMIT_TAG =~ ^(v[0-9]{1,3}.[0-9]{1,3})(.[0-9]{1,3})?(-[A-Za-z0-9]{1,20})?$ ]]
    then
      CI_TAG_VERSION=$(echo "$CI_COMMIT_TAG" | sed -e 's/-.*//')
      build=$(echo "$CI_COMMIT_TAG" | sed -e 's/.*-//')
    fi
  - echo "tag version:" $CI_TAG_VERSION

stages:
  - binary
  - uploadS3

# Build binary files
binary_build:
  stage: binary
  script:
    - go mod download
    - env GOOS=linux GOARCH=amd64 go build -a -o ${CI_PROJECT_DIR}/binary/${CI_TAG_VERSION}/linux/amd64/file-benchmark
    - env GOOS=linux GOARCH=arm64 go build -a -o ${CI_PROJECT_DIR}/binary/${CI_TAG_VERSION}/linux/arm64/file-benchmark
    - env GOOS=darwin GOARCH=amd64 go build -a -o ${CI_PROJECT_DIR}/binary/${CI_TAG_VERSION}/darwin/amd64/file-benchmark
    - env GOOS=darwin GOARCH=arm64 go build -a -o ${CI_PROJECT_DIR}/binary/${CI_TAG_VERSION}/darwin/arm64/file-benchmark
  artifacts:
    paths:
      - ./binary
    expire_in: 1 hour
  only:
    - tags

# move_binary_to_s3:
#   image: "python:latest" 
#   stage: uploadS3
#   dependencies:
#     - binary_build
#   before_script:
#     - pip install awscli # Install the SDK
#   script:
#     - aws --endpoint-url ${S3_SERVER} s3 cp ${CI_PROJECT_DIR}/binary s3://$RPM_BUCKET/file-benchmark --recursive
#   only:
#     - tags
    
